# Generated by Django 5.2.7 on 2025-10-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.CharField(blank=True, choices=[('07:30', '7:30–22:00'), ('08:00', '8:00–22:00'), ('10:00', '10:00–22:00')], max_length=5, null=True)),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coffeeshop')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='main.worker')),
            ],
            options={
                'ordering': ['date', 'worker__name'],
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
