# Generated by Django 5.2.7 on 2025-10-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshop',
            name='short_code',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
