# Generated by Django 5.2.7 on 2025-10-22 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_coffeeshop_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='other_coffee_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.coffeeshop'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='coffee_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.coffeeshop'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='main.worker'),
        ),
        migrations.CreateModel(
            name='SwapCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swaps_this_month', models.PositiveIntegerField(default=0)),
                ('month', models.DateField()),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='main.worker')),
            ],
            options={
                'unique_together': {('worker', 'month')},
            },
        ),
    ]
