# Generated by Django 5.2.7 on 2025-10-27 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_shift_other_coffee_shop_alter_shift_coffee_shop_and_more'),
    ]

    operations = [
        migrations.RunPython(
            code=lambda apps, schema_editor: update_short_codes(),
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]


def update_short_codes():
    from main.models import CoffeeShop
    
    # Обновляем short_code для кофеен
    CoffeeShop.objects.filter(id=2).update(short_code='Мр')
    CoffeeShop.objects.filter(id=3).update(short_code='Дз')
